### ISSUE TITLE
dashed lines appear solid

### ISSUE THREAD

**Issue by Riad-Jarjour** [d3plus/d3plus-plot#145] opened 2019-09-29 20:40 UTC
### Expected Behavior
Show a dashed line plot 

### Current Behavior
Lines appear solid until you hover over them once. Oddly enough this only happens when you use the plot mini-library. It works fine if you include the full d3plus library.

### Steps to Reproduce 
See https://d3plus.org/examples/d3plus-plot/custom-dashed-line-plot

Browser Name: FireFox & Chrome
Operating System and Version: Windows 10

**Comment by davelandry** [comment] 2019-10-01 17:44
thanks for reporting this @Riad-Jarjour, this should be fixed with the latest release (the example works as intended now)

**Closed** 2019-10-01 17:43 UTC
Labels: bug

**Comment by Riad-Jarjour** [comment] 2019-10-01 19:31
Probably not as important, but notice the lines don't reach the year 2018 in any of the dashed line examples until you hover over the lines once.
